### ISSUE TITLE
中青看点签到脚本

### ISSUE THREAD

**Issue by landcruser** [sazs34/MyActions#65]
https://github.com/zijide/Scripts-1，安卓的cookie好难搞啊

**Comment by sazs34** [comment]
中青看点的,可以试一下下面的,自己在.github/workflows/里面添加一个`youth.yaml`文件

然后SERCETS需要配置`YOUTH_HEADER` `YOUTH_ARTBODY` `YOUTH_REDBODY` `YOUTH_TIME` `YOUTH_NOTIFY_CONTROL` 

自己没有账号,没法尝试是否运行正常
下面是youth.yaml里面要填的内容:

```
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青看点

on:
    workflow_dispatch:
    schedule:
        - cron: "*/12 * * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【中青看点】"
              run: |
                  node onlyOneExecute.js
              env:
                  YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
                  YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
                  YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
                  YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
                  YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  JDJoyFeedCount: ${{ secrets.JDJoyFeedCount }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  SYNCURL: https://github.comert/Scripts/raw/master/Task/youth.js
```
